title: 裕仁去過哪 - 台灣
description: 介紹台灣各地的特色景點
lang: zh-TW

collections:
  attractions:
    output: true
    permalink: /attractions/:name/
  counties:
    output: true
    permalink: /counties/:name/

defaults:
  - scope:
      path: ""
      type: attractions
    values:
      layout: attraction
  - scope:
      path: ""
      type: counties
    values:
      layout: county
